#!/usr/bin/env python3
"""Create aggregate-only v4.1 report and five reproducible submission figures."""
from __future__ import annotations
import json
from pathlib import Path
import matplotlib.pyplot as plt
import pandas as pd

def main():
    root=Path("results/v4_1/frozen"); figures=root/"figures"; figures.mkdir(exist_ok=True)
    summary=json.loads((root/"normative_validation_summary.json").read_text()); inc=pd.read_csv(root/"incremental_prediction.csv"); boot=pd.read_csv(root/"incremental_bootstrap.csv"); mobi=pd.read_csv(root/"mobilised_within_between_stability.csv"); loo=pd.read_csv(root/"normative_leave_one_feature_out.csv")
    def save(name): plt.tight_layout(); plt.savefig(figures/name,dpi=220); plt.close()
    plt.figure(figsize=(6,3.5)); plt.hist(pd.read_csv(root/"normative_reference_bootstrap.csv").effect,bins=28,color="#2c7fb8"); plt.axvline(0,color="black"); plt.xlabel("Standardized severity association"); plt.title("H1: control-reference bootstrap"); save("figure_1_reference_robustness.png")
    view=inc.set_index("model"); plt.figure(figsize=(6,3.5)); plt.bar(["speed (M1)","speed + score (M2)"],[view.loc["model_1","rmse"],view.loc["model_2","rmse"]],color=["#7fcdbb","#f03b20"]); plt.ylabel("Held-out RMSE"); plt.title("H2: grouped prediction"); save("figure_2_incremental_prediction.png")
    plt.figure(figsize=(7,3.5)); plt.bar(loo.removed_feature,loo.effect,color="#756bb1"); plt.axhline(0,color="black"); plt.xticks(rotation=35,ha="right"); plt.ylabel("Association effect"); plt.title("H3: one-input-out coherence"); save("figure_3_leave_one_out.png")
    plt.figure(figsize=(6,3.5)); plt.errorbar(mobi.feature,mobi.within_effect,yerr=[mobi.within_effect-mobi.within_ci_low,mobi.within_ci_high-mobi.within_effect],fmt="o",color="#238b45"); plt.axhline(0,color="black"); plt.xticks(rotation=25,ha="right"); plt.ylabel("Within-person standardized effect"); plt.title("H5: Mobilise-D within-person model"); save("figure_4_mobilised_within_between.png")
    plt.figure(figsize=(6,3.5)); plt.bar(mobi.feature,mobi.same_direction_fraction,color=["#238b45" if x=="PASS" else "#969696" for x in mobi.stability_status]); plt.axhline(.8,color="black",linestyle="--"); plt.ylim(0,1.05); plt.xticks(rotation=25,ha="right"); plt.ylabel("Half-sample same-direction fraction"); plt.title("H5: resampling stability"); save("figure_5_mobilised_stability.png")
    ci=lambda col:(float(boot[col].quantile(.025)),float(boot[col].quantile(.975)))
    abstract=(f"Background: v4.0.6 identified an outcome-blind, eight-input control-reference gait-deviation score associated with Parkinsonian gait severity. Methods: We prespecified control-only 2,000-resample robustness, grouped held-out linear prediction, eight leave-one-input-out analyses, repeated-session equivalence auditing, and a four-feature Mobilise-D within/between model with 200 participant-half resamples. Results: The score’s association was {summary['association_effect']:.3f}; all reference resamples retained its direction (median {summary['bootstrap_median_effect']:.3f}). Adding the score to speed increased held-out rank correlation ({view.loc['model_1','spearman_rho']:.3f} to {view.loc['model_2','spearman_rho']:.3f}) but did not improve RMSE ({view.loc['model_1','rmse']:.3f} to {view.loc['model_2','rmse']:.3f}). Mobilise-D within-person effects were stable for speed and stride length, while cadence and stride duration were inconclusive. Longitudinal eight-input repeatability and external transport remain not estimable. Conclusion: The score is reference-robust and independently associated, but this sample does not establish incremental predictive improvement, repeatability, or transport; it remains a promising, not qualified, trait biomarker.")
    report=["# AAN v4.1: Validation without feature fishing","","## Abstract","",abstract,"","## Frozen results","",f"- H1 reference robustness: **{summary['h1_status']}**; same-direction fraction {summary['bootstrap_same_direction_fraction']:.3f}.",f"- H2 held-out comparison: Model 2 versus Model 1: delta MAE CI {ci('delta_mae')}, delta RMSE CI {ci('delta_rmse')}, delta Spearman rho CI {ci('delta_rho')}. RMSE did not improve, so incremental predictive value is not supported in this sample.","- H3: all eight frozen single-input ablations are presented; none replaces the original score.","- H4: `NOT_ESTIMABLE`; the authorized longitudinal release cannot reconstruct all eight PKMAS-equivalent inputs. The serialized model round-trip difference was 0.0 (tolerance <=1e-10); no model was refit.","- H5: speed and stride length passed the prespecified 0.80 same-direction stability criterion; cadence and stride duration remain incomplete.","- External eight-input transport: `NOT_ESTIMABLE`; no improvised crosswalk was created.","","## Interpretation","","The validation strengthens robustness of the original association while narrowing its claim. Association and reference stability are not sufficient for a qualified trait biomarker: repeated-session reliability and external transport remain unresolved.","","## Figures","","![Reference robustness](figures/figure_1_reference_robustness.png)","","![Grouped prediction](figures/figure_2_incremental_prediction.png)","","![Leave-one-out](figures/figure_3_leave_one_out.png)","","![Mobilise-D within-person](figures/figure_4_mobilised_within_between.png)","","![Mobilise-D stability](figures/figure_5_mobilised_stability.png)"]
    (root/"AAN_v4_1_report.md").write_text("\n".join(report)+"\n")
if __name__=="__main__": main()
